# Generated by Django 3.0.8 on 2020-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writejournal', '0004_auto_20200718_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Title', max_length=255),
        ),
    ]
